// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// 与 Next.js 的 env 优先级对齐：.env.local > .env。
// dotenv 默认 override:false（不覆盖已加载值），所以先加载 .env.local 让它占位，
// 再加载 .env 兜底。否则 prisma CLI（db push / generate）只读 .env，在仅配了
// .env.local 的环境（如线上服务器）会因 DATABASE_URL 缺失而失败。
// 文件不存在时 dotenv 静默跳过，CI（用注入的环境变量）不受影响。
loadEnv({ path: ".env.local" });
loadEnv(); // .env 兜底

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
